### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format

### ISSUE THREAD

**Issue by ahmadalibaloch** [azouaoui-med/react-pro-sidebar#159]
**Describe the bug**
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at SubMenuFR (/Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:5224:23)
    at ul
    at /Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2020:25
    at div
    at /Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2020:25
    at SubMenuContentFR (/Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:3049:23)
    at li
    at /Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2020:25
    at SubMenuFR (/Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:5224:23)
    at ul
    at /Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2020:25
    at nav
    at /Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2020:25
    at MenuFR (/Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:3009:23)
    at div
    at /Users/user_name/project_folder/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Grid (/Users/user_name/project_folder/node_modules/@mui/system/Stack/createStack.js:143:24)
    at div
    at /Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2020:25
    at aside
    at /Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2020:25
    at SidebarFR (/Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2971:17)
    at renderElement (/Users/user_name/project_folder/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at div
    at /Users/user_name/project_folder/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Grid (/Users/user_name/project_folder/node_modules/@mui/system/Stack/createStack.js:143:24)
    at Sidebar (webpack-internal:///./src/components/Sidebar/index.tsx:38:71)
    at div
    at /Users/user_name/project_folder/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Grid (/Users/user_name/project_folder/node_modules/@mui/system/Unstable_Grid/createGrid.js:64:41)
    at div
    at /Users/user_name/project_folder/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Grid (/Users/user_name/project_folder/node_modules/@mui/system/Unstable_Grid/createGrid.js:64:41)
    at Layout (webpack-internal:///./src/components/Layout/index.tsx:26:3)
    at SidebarProvider (/Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:2852:23)
    at ProSidebarProvider (/Users/user_name/project_folder/node_modules/react-pro-sidebar/dist/index.js:5421:23)
    at Hydrate (file:///Users/user_name/project_folder/node_modules/@tanstack/react-query/build/lib/Hydrate.mjs:23:3)
    at QueryClientProvider (file:///Users/user_name/project_folder/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:41:3)
    at InnerThemeProvider (/Users/user_name/project_folder/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:19:39)
    at ThemeProvider (/Users/user_name/project_folder/node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:39:5)
    at ThemeProvider (/Users/user_name/project_folder/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:38:5)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:60:3)
    at StyleRegistry (/Users/user_name/project_folder/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/Users/user_name/project_folder/node_modules/next/dist/shared/lib/router/adapters.js:60:11)
    at AppContainer (/Users/user_name/project_folder/node_modules/next/dist/server/render.js:294:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/user_name/project_folder/node_modules/next/dist/server/render.js:330:57)
    at div
    at Body (/Users/user_name/project_folder/node_modules/next/dist/server/render.js:620:21)
```
 

**To Reproduce**
1. Usage with Nextjs

**Expected behavior**
No Warnings

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser:  Chrome
 - Version : 111

**Additional context**
Usage in App.tsx:
```
            <React.StrictMode>
                <ThemeProvider theme={MUI_DEFAULT_THEME}>
                    <QueryClientProvider client={queryClient}>
                        <Hydrate state={pageProps.dehydratedState}>
                            <ProSidebarProvider>
                                <Layout>
                                    <Component {...pageProps} />
                                </Layout>
                            </ProSidebarProvider>
                        </Hydrate>
                        <ReactQueryDevtools />
                    </QueryClientProvider>
                </ThemeProvider>
            </React.StrictMode>
```

Menu.tsx

```
        <Sidebar transitionDuration={0} width="100" rootStyles={menuRootStyles}>
            {/*// calculated from header height of the sidebar*/}
            <Stack sx={{ height: 'calc(100vh - 68px)' }}>
                <Menu menuItemStyles={activeStyle}>
                    <Divider />
                    {renderMenuRecursive(NAV_MENU)}
                </Menu>
                <UserMenu />
            </Stack>
        </Sidebar>
```

**Comment by ahmadalibaloch** [comment]
Fixed it by using
`React.useLayoutEffect = React.useEffect;`
in the Menu.tsx file.
